// tslint:disable
export const TravelAppData: { [key: string]: any } = {
  'Articles Source 1': [
    { "title": "Cell 0.1", "subtitle": "Cell 0.2", "image_url": "Cell 0.3" },
    { "title": "Cell 1.1", "subtitle": "Cell 1.2", "image_url": "Cell 1.3" },
    { "title": "Cell 2.1", "subtitle": "Cell 2.2", "image_url": "Cell 2.3" },
    { "title": "Cell 3.1", "subtitle": "Cell 3.2", "image_url": "Cell 3.3" },
    { "title": "Cell 4.1", "subtitle": "Cell 4.2", "image_url": "Cell 4.3" },
    { "title": "Cell 5.1", "subtitle": "Cell 5.2", "image_url": "Cell 5.3" },
    { "title": "Cell 6.1", "subtitle": "Cell 6.2", "image_url": "Cell 6.3" },
    { "title": "Cell 7.1", "subtitle": "Cell 7.2", "image_url": "Cell 7.3" },
    { "title": "Cell 8.1", "subtitle": "Cell 8.2", "image_url": "Cell 8.3" },
    { "title": "Cell 9.1", "subtitle": "Cell 9.2", "image_url": "Cell 9.3" },
  ],
  'Articles Source 2': [
    { "title": "Cell 0.1", "subtitle": "Cell 0.2", "image_url": "Cell 0.3" },
    { "title": "Cell 1.1", "subtitle": "Cell 1.2", "image_url": "Cell 1.3" },
    { "title": "Cell 2.1", "subtitle": "Cell 2.2", "image_url": "Cell 2.3" },
    { "title": "Cell 3.1", "subtitle": "Cell 3.2", "image_url": "Cell 3.3" },
    { "title": "Cell 4.1", "subtitle": "Cell 4.2", "image_url": "Cell 4.3" },
    { "title": "Cell 5.1", "subtitle": "Cell 5.2", "image_url": "Cell 5.3" },
    { "title": "Cell 6.1", "subtitle": "Cell 6.2", "image_url": "Cell 6.3" },
    { "title": "Cell 7.1", "subtitle": "Cell 7.2", "image_url": "Cell 7.3" },
    { "title": "Cell 8.1", "subtitle": "Cell 8.2", "image_url": "Cell 8.3" },
    { "title": "Cell 9.1", "subtitle": "Cell 9.2", "image_url": "Cell 9.3" },
  ],
  'Articles Source 3': [
    { "title": "Cell 0.1", "subtitle": "Cell 0.2", "image_url": "Cell 0.3" },
    { "title": "Cell 1.1", "subtitle": "Cell 1.2", "image_url": "Cell 1.3" },
    { "title": "Cell 2.1", "subtitle": "Cell 2.2", "image_url": "Cell 2.3" },
    { "title": "Cell 3.1", "subtitle": "Cell 3.2", "image_url": "Cell 3.3" },
    { "title": "Cell 4.1", "subtitle": "Cell 4.2", "image_url": "Cell 4.3" },
    { "title": "Cell 5.1", "subtitle": "Cell 5.2", "image_url": "Cell 5.3" },
    { "title": "Cell 6.1", "subtitle": "Cell 6.2", "image_url": "Cell 6.3" },
    { "title": "Cell 7.1", "subtitle": "Cell 7.2", "image_url": "Cell 7.3" },
    { "title": "Cell 8.1", "subtitle": "Cell 8.2", "image_url": "Cell 8.3" },
    { "title": "Cell 9.1", "subtitle": "Cell 9.2", "image_url": "Cell 9.3" },
  ],
  'Articles Source 4': [
    { "title": "Cell 0.1", "subtitle": "Cell 0.2", "image_url": "Cell 0.3" },
    { "title": "Cell 1.1", "subtitle": "Cell 1.2", "image_url": "Cell 1.3" },
    { "title": "Cell 2.1", "subtitle": "Cell 2.2", "image_url": "Cell 2.3" },
    { "title": "Cell 3.1", "subtitle": "Cell 3.2", "image_url": "Cell 3.3" },
    { "title": "Cell 4.1", "subtitle": "Cell 4.2", "image_url": "Cell 4.3" },
    { "title": "Cell 5.1", "subtitle": "Cell 5.2", "image_url": "Cell 5.3" },
    { "title": "Cell 6.1", "subtitle": "Cell 6.2", "image_url": "Cell 6.3" },
    { "title": "Cell 7.1", "subtitle": "Cell 7.2", "image_url": "Cell 7.3" },
    { "title": "Cell 8.1", "subtitle": "Cell 8.2", "image_url": "Cell 8.3" },
    { "title": "Cell 9.1", "subtitle": "Cell 9.2", "image_url": "Cell 9.3" },
  ],
  'Selected Articles': [
    { "title": "Cell 0.1", "subtitle": "Cell 0.2", "image_url": "Cell 0.3" },
    { "title": "Cell 1.1", "subtitle": "Cell 1.2", "image_url": "Cell 1.3" },
    { "title": "Cell 2.1", "subtitle": "Cell 2.2", "image_url": "Cell 2.3" },
    { "title": "Cell 3.1", "subtitle": "Cell 3.2", "image_url": "Cell 3.3" },
    { "title": "Cell 4.1", "subtitle": "Cell 4.2", "image_url": "Cell 4.3" },
    { "title": "Cell 5.1", "subtitle": "Cell 5.2", "image_url": "Cell 5.3" },
    { "title": "Cell 6.1", "subtitle": "Cell 6.2", "image_url": "Cell 6.3" },
    { "title": "Cell 7.1", "subtitle": "Cell 7.2", "image_url": "Cell 7.3" },
    { "title": "Cell 8.1", "subtitle": "Cell 8.2", "image_url": "Cell 8.3" },
    { "title": "Cell 9.1", "subtitle": "Cell 9.2", "image_url": "Cell 9.3" },
  ],
};
